# Name 
name: أحمد العمودي

# Desc
description: تجارب تقنية

avatar: https://github.com/ahmadamoudi.png


footer-links:
  webpage: http://ahmd.me
  dribbble:
  email: hi@ahmd.me
  facebook:
  flickr:
  github: ahmadamoudi
  instagram:
  linkedin: ahmadamoudi
  pinterest:
  rss: #1 # ضع أي قيمة هنا لتظهر أيقونة RSS
  twitter: AhmadAmoudii
  stackoverflow: # "users/50476/bart9"
  youtube: 


disqus: ahmmd

# Google Analytics
google_analytics: UA-159925723-1


# عنوان موقعك مثلاً http://barryclark.github.io
# يستخدم هذا المتغير في الـRSS والـSitemap.xml
url: # https://ahmdmo.github.io

# إذا كانت المدونة خاصة للصفحات المشاريع في GitHub (http://yourusername.github.io/repository-name مثلاً) عدل هذا المتغير ليطابق اسم المشروع
baseurl: ""


# Jekyll variables

permalink: /blog/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
